- name: Test connectivity for enrollment to wazuh server
  ansible.builtin.wait_for:
    host: "{{ wazuh_agent_wazuh_manager }}"
    port: "{{ wazuh_agent_enrollment_port }}"
    timeout: 5
    state: started

- name: Set wazuh agent name
  ansible.builtin.set_fact:
    wazuh_agent_hostname: "{{ ansible_hostname }}"

- name: Build download uri
  ansible.builtin.set_fact:
    wazuh_agent_hostname: "{{ ansible_hostname }}"

- name: Running on distributions based on {{ ansible_os_family }}
  ansible.builtin.include_tasks: "_{{ ansible_os_family | lower }}-tasks.yml"
  tags: install-wazuh-agent

- name: Create file for password authentication
  when: wazuh_agent_password is defined
  ansible.builtin.copy:
    dest: /var/ossec/etc/authd.pass
    content: "{{ wazuh_agent_password }}"
    mode: "640"
    owner: root:wazuh
